var entryList = [{day: 1, titgile: "Orientation with John Wark.", text: "Mostly average stuff, going over policies and basic house manners. <h3>Installated text editor, gitbash, ect.</h3>No great trouble with most installs, felt pretty comfortable with command line but needed brushing up.  Think we got Zsh installed, which was the hardest.", publishDate: "April 3rd, 2017"},
{day: 2, title: "Watched Cohort 18 capstones.", text: "Some pretty impressive projects, a few not.  My goal is definitely to make one better than what I saw.  Some of the better ones were: coffee snob, wig finder.  Having a hardtime remember lots of individual ones.<h3>Questions for Brenda and free work time.</h3>Visual Studio seems like it is for people much further along than this.  Worked on this exercise - presonal blog page.", publishDate: "April 4th, 2017"},
{day: 3, title: "Demo'd HTML &amp; CSS.", text: "Built Wizard of Oz page with some links, pictures, and css.  Mostly review of prework and what I already know, just brushing up.<h3>Learned about repos and committing.</h3>My quick steps for creating repo:<br><ol><li>Create repo on github account - Note:consider readme.md creation.</li><li>With terminal, change directory to where you want repo.</li><li>Enter 'git init'.</li><li>Add all files to repo, ie. 'git add filename.type'.</li><li>Commit files, ie git commit -m 'message'.</li><li>Enter 'git remote add origin <i>givendestinationfromgithub</i>'.</li><li>Push, ie. 'git push -u origin master'.</li></ol>.", publishDate: "April 5th, 2017"},
{day: 4, title: "Practiced Git Flow.", text: "Learned about push, pull, pull request, merging, and branching.  Practiced a few iterations of the loop.  I understand the importance of the flow for team projects, having a master that is the same for everyone.<h3>Steve Presented Education Strategy</h3>The most important things of teamwork- communication and compassion.  Surprised at first to see compassion there.  Also, adult learning is best done by revisiting topics after a few days, to cement knowledge.  After this we had some time for free work.", publishDate: "April 6th, 2017"},
{day: 5, title: "Free Work", text: "Finished almost all the exercises, minus the HTML ones, which I work on as I write this.  Some other students started a group challenge, and I want in, but it got too far along before I knew.  Currently stuck on a javascript exercise, the Temp converter.  I have often had a hard time bridging between different files, ie. getting info from html page and using it in javascript.", publishDate: "April 7th, 2017"},
{day: 6, title: "Javascript Brendalong", text: "I write this rather late, but as I remember we did a few random projects illustrating the powers of javascript. Relatively easy stuff for me, as I have worked with Java and loops before.", publishDate: "April 17th, 2017"},
{day: 7, title: "More Javascript and Looping practice", text: "Again, writing this late, so don't recall a lot of details", publishDate: "April 17th, 2017"},
{day: 8, title: "Started group project", text: "My group lead was Kathy, with teammates Jordan and Preeti. We based a page off of a theme we saw on wordpress that featured a bottom nav bar that was fixed. Our product was doggy dates, enjoying having a dog without the responsibility. I did the index page with nav bar.", publishDate: "April 17th, 2017"},
{day: 9, title: "Continued Project.", text: "I also did the Javascript for loading up our dogs on the product page. Together with help from Jordan, styled it out and Kathy made the dog products to fill array. I have noticed myself taking more leadership roles when Kathy lacked direction or strength.<h3>Presented projects</h3>Our site turned out pretty great. There was one project I think I liked better than ours, Watches, but my JS was better than theirs. We were also assigned the same project with a new group.", publishDate: "April 17thd, 2017"},
{day: 10, title: "New Project", text: "With Andrew as team lead, myself, Ruthie and Ollie made a website that was a spoof on the Eat Well site from downstairs. In this project we worked more on the git project flow and using tickets. Andrew was a good manager in that, creating a good frame for working as well as the focus to follow through with it. I did the navbar and footer as well as the index page which I am pretty proud of, looks just like theirs.", publishDate: "April 17th, 2017"},
{day: 11, title: "Presented Project", text: "There was a few projects I like. One used an API which I would like to learn about incorporating. I also would like to make pages that have a like element, ie. navbar or footer, and use javascript to show them, so you don't have to edit each page if you make a modification.<h3>Milestone Challenges</h3>We had free time to work on our milestones. Thought I finished the JS one, but forgot about some requirements.", publishDate: "April 17th, 2017"},
{day: 12, title: "Event Listeners Code Along", text: "Practiced some cool functionalities of event listeners with Brenda.  I am familiar with them, but I feel much better about my understanding of them than ever before.  Using the developer tools, you can get tons of information that is available for them.<h3>Free Work</h3>Finished the JS milestone.  Worked on the HTML/CSS one.", publishDate: "April 19th, 2017"}
]
var blog = document.getElementById("blog");
var blogText = "";

entryList.forEach(function (entry) {
	blogText += "<article><h4>Day " + entry.day + "</h4><h3>" + entry.title + "</h3>" + entry.text +"<br>by Jason Smith on " + entry.publishDate + "</article>";
});
blog.innerHTML = blogText;